import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "@/components/NavBar/Navbar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "LootLab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <NavBar />
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
